name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: luoch
        password: ${{ secrets.DOCKER_HUB_KEY }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker buildx create --use
        docker run --privileged --rm tonistiigi/binfmt --install all
        docker buildx build -f Dockerfile --push --platform linux/arm64,linux/amd64 --tag luoch/progress.go:1.0.4 .
